plugins {
    id 'java'
}

group = 'LearAumatingApps'
version = '1.0-SNAPSHOT'



repositories {
    mavenCentral()
    maven { url "https://hub.browserstack.com/maven" }
}

dependencies {
    implementation 'io.appium:java-client:9.5.0'
    implementation 'org.testng:testng:7.11.0'
    implementation 'org.seleniumhq.selenium:selenium-java:4.34.0'
    implementation 'commons-io:commons-io:2.20.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.19.2'
    implementation 'com.aventstack:extentreports:5.1.2'


}

//def browserstackSDKArtifact = configurations.compileClasspath.resolvedConfiguration.resolvedArtifacts.find { it.name == 'browserstack-java-sdk' }

// -------------------- LOCAL --------------------
test {
    useTestNG {
        suites "testng.xml"
    }
    systemProperty "USE_BROWSERSTACK", "false"
    systemProperty "deviceName", System.getProperty("deviceName", "emulator-5554")
    systemProperty "platformVersion", System.getProperty("platformVersion", "11")

    doFirst { println "▶ Running LOCAL tests" }
}

// -------------------- BROWSERSTACK --------------------




