#bsUsername=sanjeev_efWR7h
#bsAccessKey=BrUyx5M5aC3uabP5s3sQ
#bsAppId=bs://e00f1482142eb25279affa9605b5ded0396b8fec
#deviceName=Google Pixel 5
#platformVersion=12.0

bsUsername=sanjeev_efWR7h
bsAccessKey=BrUyx5M5aC3uabP5s3sQ
bsAppId=bs://e00f1482142eb25279affa9605b5ded0396b8fec

# Local defaults (optional)
deviceName=emulator-5554
platformVersion=11

